name: dart-solana-lib

packages:
  - '**'

scripts:
  check_master:
    run: |
      melos run get \
      && melos run format \
      && melos run analyze \
      && melos run test

  get: pub get

  build: pub run build_runner build

  format: dart format --set-exit-if-changed -o none .

  analyze: dart analyze --fatal-infos .

  test: pub run test
