name: solana
version: 0.3.1
repository: https://github.com/antoineherzog/dart-solana-lib
description: >-
  Simple library to interact with the Solana blockchain

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  bip39: '>=1.0.3 <1.0.6'
  convert: ^2.1.1
  cryptography: ^1.4.1
  http: ^0.12.2
  json_annotation: ^3.1.1
  meta: ^1.2.4
  test: ^1.15.7

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  mews_pedantic: ^0.2.0

